[package]
name = "hyperlane-utils"
version = "2.1.5"
edition = "2024"
authors = ["root@ltpp.vip"]
license = "MIT"
description = """A library providing utils for hyperlane."""
keywords = ["http", "request", "response", "tcp", "redirect"]
repository = "https://github.com/hyperlane-utils/hyperlane-utils.git"
categories = ["network-programming", "web-programming"]
exclude = [
    "target",
    "Cargo.lock",
    "sh",
    ".github"
]

[dependencies]
hex = "0.4.3"
lombok-macros = "1.13.7"
serde = "1.0.219"
serde-xml-rs = "0.8.1"
serde_json = "1.0.141"
serde_urlencoded = "0.7.1"
url = "2.5.4"
once_cell = "1.21.3"
simd-json = "0.15.1"
futures = "0.3.31"
num_cpus = "1.17.0"
ahash = "0.8.12"
urlencoding = "2.1.3"
twox-hash = "2.1.1"
chunkify = "0.6.7"
future-fn = "0.3.1"
color-output = "7.2.1"
clonelicious = "2.2.1"
hyperlane-log = "1.18.4"
server-manager = "3.5.0"
file-operation = "0.8.1"
compare_version = "1.2.0"
bin-encode-decode = "1.1.1"
recoverable-spawn = "3.9.1"
hyperlane-broadcast = "0.7.3"
recoverable-thread-pool = "2.4.1"
log = "0.4.27"
std-macro-extensions = "0.26.1"
hot-restart = "0.5.1"
utoipa = { version = "5.4.0", features = ["openapi_extensions"] }
utoipa-swagger-ui = { version = "9.0.2", features = ["debug-embed", "vendored", "actix-web"] }
utoipa-rapidoc = { version = "6.0.0", features = ["actix-web"] }
hyperlane-macros = "1.10.4"
hyperlane-plugin-websocket = "2.2.4"

[profile.dev]
incremental = false
opt-level = 3
lto = true
panic = "unwind"
debug = false
codegen-units = 1
strip = "debuginfo"

[profile.release]
incremental = false
opt-level = 3
lto = true
panic = "unwind"
debug = false
codegen-units = 1
strip = "debuginfo"
